#!/usr/bin/env bash
# Transfer file from client to server
# Accepts four parameters
#	-Path to the file to be transfered
#	-IP of the server
#	-Username scp connects with
#	-Path the the private key scp connects with

if [ "$4" ]; then
	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~"
elif [ "$3" ]; then
	scp -o StrictHostKeyChecking=no "$1" "$3@$2:~"
else
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
fi
