#!/usr/bin/env bash
# Install the nginx server listening on port 80
# When we query nginx at the root it returns a page containing  a string "Hello World"

apt update
apt install -y nginx
ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.html
service nginx restart
